In [ ]:
"hello"

'hello'

In [1]:
import pandas as pd   # type: ignore

In [ ]:
pd.__version__

'2.2.3'

key Data Structures
Series = one list
DataFrame = Full table

Panda Series

Create Series

sales = pd.series([2,3,5])

In [ ]:
sales = pd.Series([2,3,5,4,8,7])

In [ ]:
sales

0    2
1    3
2    5
3    4
4    8
5    7
dtype: int64

In [ ]:
sales[2]

np.int64(5)

In [ ]:
sales[0:2]

0    2
1    3
dtype: int64

In [ ]:
sales.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
sales.values

array([2, 3, 5, 4, 8, 7])

In [ ]:
sales.dtype

dtype('int64')

In [ ]:
sales.head

<bound method NDFrame.head of 0    2
1    3
2    5
3    4
4    8
5    7
dtype: int64>

In [ ]:
sales.tail

<bound method NDFrame.tail of 0    2
1    3
2    5
3    4
4    8
5    7
dtype: int64>

In [ ]:
sales.sort_values(ascending=True)

0    2
1    3
3    4
2    5
5    7
4    8
dtype: int64

In [ ]:
sales.isnull

<bound method Series.isnull of 0    2
1    3
2    5
3    4
4    8
5    7
dtype: int64>

In [ ]:
sales.head(2)

0    2
1    3
dtype: int64

In [ ]:
sales.count()

np.int64(6)

In [ ]:
sales.isnull()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [ ]:
sales.notnull()

0    True
1    True
2    True
3    True
4    True
5    True
dtype: bool

In [ ]:
sales + 1

0    3
1    4
2    6
3    5
4    9
5    8
dtype: int64

In [ ]:
sales

0    2
1    3
2    5
3    4
4    8
5    7
dtype: int64

In [ ]:
sales *2

0     4
1     6
2    10
3     8
4    16
5    14
dtype: int64

In [ ]:
sales.tail(2)

4    8
5    7
dtype: int64

In [2]:
sales_missing = pd.Series([2, None, 5])

In [3]:
sales_missing.isnull()

0    False
1     True
2    False
dtype: bool

In [ ]:
sales_missing.notnull()

0     True
1    False
2     True
dtype: bool

In [ ]:
sales_missing.fillna(3)

0    2.0
1    3.0
2    5.0
dtype: float64

In [ ]:
sales_missing = pd.Series([2, None, 5])

In [ ]:
sales_missing =  sales_missing.fillna(3)

In [ ]:
sales_missing

0    2.0
1    3.0
2    5.0
dtype: float64

In [4]:
si = pd.Series(data = [100,200,300,400,500], index=list('abcde'))

In [5]:
si

a    100
b    200
c    300
d    400
e    500
dtype: int64

In [ ]:
si.info()

<class 'pandas.core.series.Series'>
Index: 5 entries, a to e
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 252.0+ bytes

In [8]:
df = pd.DataFrame({
    'age': [24,25,29],
    'city': ['Linz','Graz','Vienna']
    }, index=['Alice','Bob','Charlie']
)

In [ ]:
print(df)

         age    city
Alice     24    Linz
Bob       25    Graz
Charlie   29  Vienna

In [ ]:
df['age']

Alice      24
Bob        25
Charlie    29
Name: age, dtype: int64

In [ ]:
print(df[df['age']>24])

         age    city
Bob       25    Graz
Charlie   29  Vienna

here 3 is number of rows and 2 is a number of colulmns.

In [9]:
df.shape

(3, 2)

In [13]:
si.shape

(5,)

In [15]:
df.columns

Index(['age', 'city'], dtype='object')

In [16]:
df.dtypes

age      int64
city    object
dtype: object

Accessing Data
#using labels
df.loc[1,'age']

#using index
df.iloc[1,0]

In [18]:
df

         age    city
Alice     24    Linz
Bob       25    Graz
Charlie   29  Vienna

In [28]:
df.loc["Alice"]

age       24
city    Linz
Name: Alice, dtype: object

In [25]:
print(df.index)

Index(['Alice', 'Bob', 'Charlie'], dtype='object')

In [30]:
df.loc['Charlie']

age         29
city    Vienna
Name: Charlie, dtype: object

In [31]:
df.loc['Charlie', "city"]

'Vienna'

In [38]:
df.iloc[1]

age       25
city    Graz
Name: Bob, dtype: object

In [39]:
df.iloc[2,0]

np.int64(29)

In [40]:
df.head()

         age    city
Alice     24    Linz
Bob       25    Graz
Charlie   29  Vienna

In [41]:
df.tail()

         age    city
Alice     24    Linz
Bob       25    Graz
Charlie   29  Vienna

In [42]:
df.count()

age     3
city    3
dtype: int64

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Alice to Charlie
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     3 non-null      int64
 1   city    3 non-null      object
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

In [45]:
df.describe()

             age
count   3.000000
mean   26.000000
std     2.645751
min    24.000000
25%    24.500000
50%    25.000000
75%    27.000000
max    29.000000