A DataFrame is a 2-d data structure that can store data of different types (including characters, integers, floating point, values, categorical data and more) in columns. It is similar to a spreadsheet,a sql table or the data.frame in R.

The table has 3 columns, each of them with a column label. The column labels are respectively Name, Age and Sex.

The column Name consists of textual data with each value a string, the column Age are numbers and the column Sex is textual data.

The index labels each row. By default, this is a sequence of integers starting at 0.

Each columns in a dataframe is a series.

In [6]:
import pandas as pd

In [10]:
df = pd.DataFrame({
            "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
})

In [12]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2   Bonnell, Miss Elizabeth   58  female

I'm just interested in working with the data in the column Age.
%pip install pandas

In [15]:
df["Age"]

0    22
1    35
2    58
Name: Age, dtype: int64

When selecting a single column of a pandas DataFrame, the result is a pandas Series. To select the column, use the column label in between square brackets.

You can create a series from a scratch as well.

In [16]:
ages = pd.Series([22,35,58], name = "Age")

In [17]:
ages

0    22
1    35
2    58
Name: Age, dtype: int64

A pandas Series has no column labels, as it is just a single column of a DataFrame. A series does have row labels.

In [18]:
# I want to know the maximum age of the passangers.
# we can do this on the DataFrame by selecting the Age column and applying max()

df["Age"].max()

np.int64(58)

In [21]:
# or on the series
ages.max()

np.int64(58)

In [ ]:
df.describe()
# The describe() method provides a quick overview of the numerical data in a DataFrame. As the Name and sex columlns are textual data, these are by default no taken into account by the describe method.

             Age
count   3.000000
mean   38.333333
std    18.230012
min    22.000000
25%    28.500000
50%    35.000000
75%    46.500000
max    58.000000