In [1]:
import pandas as pd

In [8]:
data = {
    "name": [
        "Aditya", "Rahul", "Maria", "John", "Sophia",
        "Daniel", "Emma", "Liam", "Olivia", "Noah",
        "Mia", "James", "Ava", "Lucas", "Isabella"
    ],
    "age": [
        29, 24, 31, 22, 27,
        35, 23, 30, 26, 32,
        28, 21, 34, 25, 29
    ],
    "city": [
        "Linz", "Vienna", "Salzburg", "Linz", "Graz",
        "Vienna", "Linz", "Graz", "Vienna", "Salzburg",
        "Linz", "Graz", "Vienna", "Linz", "Salzburg"
    ],
    "department": [
        "IT", "Marketing", "HR", "IT", "Finance",
        "IT", "HR", "Marketing", "IT", "Finance",
        "IT", "HR", "Marketing", "IT", "Finance"
    ],
    "salary": [
        52000, 35000, 48000, 39000, 52000,
        61000, 33000, 45000, 57000, 50000,
        44000, 38000, 55000, 41000, 53000
    ],
    "experience": [
        2, 1, 7, 1, 4,
        10, 1, 6, 5, 8,
        3, 2, 9, 2, 6
    ],
    "age_group": [
        "20s", "20s", "30s", "20s", "20s",
        "30s", "20s", "30s", "20s", "30s",
        "20s", "20s", "30s", "20s", "20s"
    ],
    "remote": [
        True, False, True, False, True,
        True, False, True, True, False,
        True, False, True, False, True
    ]
}

In [9]:
df = pd.DataFrame(data)

In [10]:
df

        name  age      city department  salary  experience age_group  remote
0     Aditya   29      Linz         IT   52000           2       20s    True
1      Rahul   24    Vienna  Marketing   35000           1       20s   False
2      Maria   31  Salzburg         HR   48000           7       30s    True
3       John   22      Linz         IT   39000           1       20s   False
4     Sophia   27      Graz    Finance   52000           4       20s    True
5     Daniel   35    Vienna         IT   61000          10       30s    True
6       Emma   23      Linz         HR   33000           1       20s   False
7       Liam   30      Graz  Marketing   45000           6       30s    True
8     Olivia   26    Vienna         IT   57000           5       20s    True
9       Noah   32  Salzburg    Finance   50000           8       30s   False
10       Mia   28      Linz         IT   44000           3       20s    True
11     James   21      Graz         HR   38000           2       20s   False
12       Ava   34    Vienna  Marketing   55000           9       30s    True
13     Lucas   25      Linz         IT   41000           2       20s   False
14  Isabella   29  Salzburg    Finance   53000           6       20s    True

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        15 non-null     object
 1   age         15 non-null     int64
 2   city        15 non-null     object
 3   department  15 non-null     object
 4   salary      15 non-null     int64
 5   experience  15 non-null     int64
 6   age_group   15 non-null     object
 7   remote      15 non-null     bool
dtypes: bool(1), int64(3), object(4)
memory usage: 987.0+ bytes

In [12]:
df.describe()

             age        salary  experience
count  15.000000     15.000000   15.000000
mean   27.733333  46866.666667    4.466667
std     4.267262   8408.046033    3.067495
min    21.000000  33000.000000    1.000000
25%    24.500000  40000.000000    2.000000
50%    28.000000  48000.000000    4.000000
75%    30.500000  52500.000000    6.500000
max    35.000000  61000.000000   10.000000

In [13]:
df[df["salary"]<45000]

     name  age    city department  salary  experience age_group  remote
1   Rahul   24  Vienna  Marketing   35000           1       20s   False
3    John   22    Linz         IT   39000           1       20s   False
6    Emma   23    Linz         HR   33000           1       20s   False
10    Mia   28    Linz         IT   44000           3       20s    True
11  James   21    Graz         HR   38000           2       20s   False
13  Lucas   25    Linz         IT   41000           2       20s   False

Adding the columns 
df['column-name'] = [values,]

In [14]:
df['Gender']= [
        "Male", "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female"
    ]

In [15]:
df

,name,age,city,department,salary,experience,age_group,remote,Gender
0,Aditya,29,Linz,IT,52000,2,20s,True,Male
1,Rahul,24,Vienna,Marketing,35000,1,20s,False,Male
2,Maria,31,Salzburg,HR,48000,7,30s,True,Female
3,John,22,Linz,IT,39000,1,20s,False,Male
4,Sophia,27,Graz,Finance,52000,4,20s,True,Female
5,Daniel,35,Vienna,IT,61000,10,30s,True,Male
6,Emma,23,Linz,HR,33000,1,20s,False,Female
7,Liam,30,Graz,Marketing,45000,6,30s,True,Male
8,Olivia,26,Vienna,IT,57000,5,20s,True,Female
9,Noah,32,Salzburg,Finance,50000,8,30s,False,Male
10,Mia,28,Linz,IT,44000,3,20s,True,Female
11,James,21,Graz,HR,38000,2,20s,False,Male
12,Ava,34,Vienna,Marketing,55000,9,30s,True,Female
13,Lucas,25,Linz,IT,41000,2,20s,False,Male
14,Isabella,29,Salzburg,Finance,53000,6,20s,True,Female

Drop/ Delete the columns

del df['Gender']

In [16]:
del df['Gender']

In [17]:
df

        name  age      city department  salary  experience age_group  remote
0     Aditya   29      Linz         IT   52000           2       20s    True
1      Rahul   24    Vienna  Marketing   35000           1       20s   False
2      Maria   31  Salzburg         HR   48000           7       30s    True
3       John   22      Linz         IT   39000           1       20s   False
4     Sophia   27      Graz    Finance   52000           4       20s    True
5     Daniel   35    Vienna         IT   61000          10       30s    True
6       Emma   23      Linz         HR   33000           1       20s   False
7       Liam   30      Graz  Marketing   45000           6       30s    True
8     Olivia   26    Vienna         IT   57000           5       20s    True
9       Noah   32  Salzburg    Finance   50000           8       30s   False
10       Mia   28      Linz         IT   44000           3       20s    True
11     James   21      Graz         HR   38000           2       20s   False
12       Ava   34    Vienna  Marketing   55000           9       30s    True
13     Lucas   25      Linz         IT   41000           2       20s   False
14  Isabella   29  Salzburg    Finance   53000           6       20s    True

In [18]:
df

        name  age      city department  salary  experience age_group  remote
0     Aditya   29      Linz         IT   52000           2       20s    True
1      Rahul   24    Vienna  Marketing   35000           1       20s   False
2      Maria   31  Salzburg         HR   48000           7       30s    True
3       John   22      Linz         IT   39000           1       20s   False
4     Sophia   27      Graz    Finance   52000           4       20s    True
5     Daniel   35    Vienna         IT   61000          10       30s    True
6       Emma   23      Linz         HR   33000           1       20s   False
7       Liam   30      Graz  Marketing   45000           6       30s    True
8     Olivia   26    Vienna         IT   57000           5       20s    True
9       Noah   32  Salzburg    Finance   50000           8       30s   False
10       Mia   28      Linz         IT   44000           3       20s    True
11     James   21      Graz         HR   38000           2       20s   False
12       Ava   34    Vienna  Marketing   55000           9       30s    True
13     Lucas   25      Linz         IT   41000           2       20s   False
14  Isabella   29  Salzburg    Finance   53000           6       20s    True

In [23]:
df = df.drop(columns='Gender')

KeyError: "['Gender'] not found in axis"

In [20]:
df

        name  age      city department  salary  experience age_group  remote
0     Aditya   29      Linz         IT   52000           2       20s    True
1      Rahul   24    Vienna  Marketing   35000           1       20s   False
2      Maria   31  Salzburg         HR   48000           7       30s    True
3       John   22      Linz         IT   39000           1       20s   False
4     Sophia   27      Graz    Finance   52000           4       20s    True
5     Daniel   35    Vienna         IT   61000          10       30s    True
6       Emma   23      Linz         HR   33000           1       20s   False
7       Liam   30      Graz  Marketing   45000           6       30s    True
8     Olivia   26    Vienna         IT   57000           5       20s    True
9       Noah   32  Salzburg    Finance   50000           8       30s   False
10       Mia   28      Linz         IT   44000           3       20s    True
11     James   21      Graz         HR   38000           2       20s   False
12       Ava   34    Vienna  Marketing   55000           9       30s    True
13     Lucas   25      Linz         IT   41000           2       20s   False
14  Isabella   29  Salzburg    Finance   53000           6       20s    True

In [24]:
df[df["department"]== "IT"]

      name  age    city department  salary  experience age_group  remote
0   Aditya   29    Linz         IT   52000           2       20s    True
3     John   22    Linz         IT   39000           1       20s   False
5   Daniel   35  Vienna         IT   61000          10       30s    True
8   Olivia   26  Vienna         IT   57000           5       20s    True
10     Mia   28    Linz         IT   44000           3       20s    True
13   Lucas   25    Linz         IT   41000           2       20s   False

In [25]:
df[df["city"] == "Linz"]

      name  age  city department  salary  experience age_group  remote
0   Aditya   29  Linz         IT   52000           2       20s    True
3     John   22  Linz         IT   39000           1       20s   False
6     Emma   23  Linz         HR   33000           1       20s   False
10     Mia   28  Linz         IT   44000           3       20s    True
13   Lucas   25  Linz         IT   41000           2       20s   False